AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  paramVPC:
    Type: String
    Default: 192.168.100.0/24
  paramPublicSubnet:
    Type: String
    Default: 192.168.100.0/25
  paramPrivateSubnet:
    Type: String
    Default: 192.168.100.128/25
  paramUniqueName:
    Type: String
    Default: cf-testing

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref paramVPC
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref paramUniqueName

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref paramPublicSubnet
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Ref paramUniqueName

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref paramPrivateSubnet
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Ref paramUniqueName

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref paramUniqueName

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  DefaultSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: cf-testing default security group for VPC
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Ref paramUniqueName
      SecurityGroupIngress:
        - IpProtocol: -1  # Allows all traffic
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0  # Allow all inbound traffic (not recommended for production)
      SecurityGroupEgress:
        - IpProtocol: -1  # Allows all outbound traffic
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

Outputs:
  VPCId:
    Value: !Ref MyVPC
  InternetGatewayId:
    Value: !Ref MyInternetGateway
  DefaultSecurityGroupId:
    Value: !Ref DefaultSecurityGroup
  PublicSubnetId:
    Value: !Ref PublicSubnet
  PrivateSubnetId:
    Value: !Ref PrivateSubnet