AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PublicSubnetId:
    Type: String
  PrivateSubnetId:
    Type: String
  VPCId:
    Type: String
  ImageId:
    Type: String
    Default: ami-0866a3c8686eaeeba
  KtxPublicIp:
    Type: String
    Default: 14.169.82.131/32
  ZonePublicIp:
    Type: String
    Default: 18.206.107.24/29

Resources:
  PublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref PublicSecurityGroup
      KeyName: testkeypair
      ImageId: !Ref ImageId
      Tags:
        - Key: Name
          Value: idk-test-public-ec2

  PrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref ImageId
      NetworkInterfaces:
        - GroupSet:
          - !Ref PrivateSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref PrivateSubnetId
      KeyName: testkeypair
      Tags:
        - Key: Name
          Value: idk-test-private-ec2

  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access from specific IP
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref ZonePublicIp
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref KtxPublicIp

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access from Public instance
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          SourceSecurityGroupId: !Ref PublicSecurityGroup

Outputs:
  PublicEC2InstanceId:
    Value: !Ref PublicEC2Instance
  PrivateEC2InstanceId:
    Value: !Ref PrivateEC2Instance
