AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://idk-testing.s3.amazonaws.com/vpc.yaml

  NatGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://idk-testing.s3.amazonaws.com/nat-gateway.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        InternetGatewayId: !GetAtt VPCStack.Outputs.InternetGatewayId

  RouteTableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://idk-testing.s3.amazonaws.com/route-table.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        InternetGatewayId: !GetAtt VPCStack.Outputs.InternetGatewayId
        NatGatewayId: !GetAtt NatGatewayStack.Outputs.NatGatewayId

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://idk-testing.s3.amazonaws.com/ec2.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId