AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  # Parameters to specify existing VPC, subnets, and the Internet Gateway ID
  VPCId:
    Type: String
  PublicSubnetId:
    Type: String   # Public subnet where the NAT Gateway will be deployed
  PrivateSubnetId:
    Type: String   # This parameter is not directly used but may be part of future routing setup
  InternetGatewayId:
    Type: String
  paramUniqueName:
    Type: String
    Default: cf-testing  # Default name for tagging resources

Resources:
  
  # Elastic IP to be associated with the NAT Gateway
  EIPForNAT:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC  # The Elastic IP will be in the VPC domain
      Tags:
      - Key: Name
        Value: !Ref paramUniqueName   # Tag with a unique name for identification

  # NAT Gateway for allowing private subnet instances to access the internet
  MyNatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIPForNAT.AllocationId  # Use the EIP for the NAT Gateway
      SubnetId: !Ref PublicSubnetId  # The NAT Gateway is placed in the public subnet
      Tags:
        - Key: Name
          Value: !Ref paramUniqueName   # Tag with a unique name for identification

Outputs:
  # Output the ID of the created NAT Gateway
  NatGatewayId:
    Value: !Ref MyNatGateway
